
services:
  tentris-db:
    image: ghcr.io/tentris/tentris:latest
    container_name: hackathon-db
    restart: unless-stopped
    
    env_file:
      - ./src/tentris-server/tentris.env
      
    environment:
      - TENTRIS_RDF_FILE=/app/instance_data.ttl
      
    ports:
      - "9080:9080"
      
    volumes:
      - ./src/tentris-server/tentris-license.toml:/config/tentris-license.toml:ro
      - ./src/tentris-server/tentris-server-config.toml:/config/tentris-server-config.toml:ro
      - ./src/tentris-server/instance_data.ttl:/app/instance_data.ttl:ro
      
      - tentris_data:/data
      
volumes:
  tentris_data: