# Hackathon Server Configuration

[serve]
read-only = false
bind-address = "[::]:9080"
limit-concurrent-requests = 64
limit-query-duration-secs = 180
limit-sparql-response-body-size = 1073741824

[serve.auth]
allow-guests = true
